### ISSUE TITLE
[BUG] Unable to link nodes when using docker-compose

### ISSUE THREAD

**Issue by jack-ullery** [coreemu/core#901]
**Describe the bug**
I cannot seem to create a simple test with two linked docker nodes, using docker compose.
![image](https://github.com/user-attachments/assets/5e3c4c30-881c-4364-8ea2-f98de2bbf259)

Using the [Discord message history](https://discord.com/channels/382277735575322625/382277735575322627/1200356435343720448) as reference, I created the following `docker-compose.yml` file:
```
version: "3.1"
services:
  n1:
    image: ubuntu:jammy
    container_name: ${node.name}
    network_mode: none
    command: tail -f /dev/null
  n2:
    image: ubuntu:jammy
    container_name: ${node.name}
    network_mode: none
    command: tail -f /dev/null
```

Unfortunately, starting a CORE test with this setup will lead to an error:
![image](https://github.com/user-attachments/assets/1472e465-e492-468c-907e-9ab579db6fd4)

If I remove the `network_mode: none` lines from the docker-compose.yml, I get the following error:
![image](https://github.com/user-attachments/assets/0d8938dd-6031-4a74-840b-e6e142debf15)

In either case, the error is resolved if I unlink the nodes.

**To Reproduce**
1. Create the following file `test.xml`:
```
<?xml version='1.0' encoding='UTF-8'?>
<scenario>
  <networks/>
  <devices>
    <device id="1" name="n1" icon="" canvas="1" type="" class="docker" image="ubuntu:jammy" compose="/tmp/core-docker/docker-compose.yml" compose_name="n1">
      <position x="138.0" y="138.0" lat="-1.2396750920849298e-05" lon="1.2396750920849395e-05" alt="0.0"/>
    </device>
    <device id="2" name="n2" icon="" canvas="0" type="" class="docker" image="ubuntu:jammy" compose="/tmp/core-docker/docker-compose.yml" compose_name="n2">
      <position x="402.0" y="138.0" lat="-1.2396750920849298e-05" lon="3.611227442160475e-05" alt="0.0"/>
    </device>
  </devices>
  <links>
    <link node1="1" node2="2">
      <iface1 id="0" name="eth0" ip4="10.0.0.20" ip4_mask="24" ip6="2001::14" ip6_mask="64"/>
      <iface2 id="0" name="eth0" ip4="10.0.0.21" ip4_mask="24" ip6="2001::15" ip6_mask="64"/>
      <options delay="0" bandwidth="0" loss="0.0" dup="0" jitter="0" unidirectional="0" buffer="0"/>
    </link>
  </links>
</scenario>
```
2. Create the following `docker-compose.yml`
```
version: "3.1"
services:
  n1:
    image: ubuntu:jammy
    container_name: ${node.name}
    network_mode: none
    command: tail -f /dev/null
  n2:
    image: ubuntu:jammy
    container_name: ${node.name}
    network_mode: none
    command: tail -f /dev/null
```
3. Create a soft-link to the current directory (for portability): `ln -s $(pwd) /tmp/core-docker`
4. Start `core-daemon`, open the xml in `core-gui`, and click the green button to start the scenario.
5. Observe the following error:
```
command(nsenter -t 116063 -n -- ip address add 2001::14/64 dev eth0), status(2):
stdout: 
stderr: Error: ipv6: IPv6 is disabled on this device.
```
6. Remove the `network_mode` field from the yaml:
```
version: "3.1"
services:
  n1:
    image: ubuntu:jammy
    container_name: ${node.name}
    command: tail -f /dev/null
  n2:
    image: ubuntu:jammy
    container_name: ${node.name}
    command: tail -f /dev/null
```
7. Restart the scenario, and observe the following error:
```
command(nsenter -t 115389 -n -- ip link set veth1.0.4 name eth0), status(2):
stdout: 
stderr: RTNETLINK answers: File exists
```

**Expected behavior**
We should be able to start the scenario without error.

**Desktop Information:**
 - OS: Ubuntu 22.04.5 LTS
 - CORE Version: Latest commit on the master branch: f7d2e857c674c0100fcc53580e447063794c5f54
 - EMANE Version: 1.5.1

**Additional context**
So that you have additional information about the docker on my system:

The contents of my `/etc/docker/daemon.json`:
``` 
{
  "bridge": "none",
  "iptables": false
}
```

Results of `dpkg --list | grep docker`:
```
ii  docker-compose                             1.29.2-1                                all          define and run multi-container Docker applications with YAML
ii  docker-compose-v2                          2.24.6+ds1-0ubuntu1~22.04.1             amd64        tool for running multi-container applications on Docker
ii  docker.io                                  24.0.7-0ubuntu2~22.04.1                 amd64        Linux container runtime
ii  python3-docker                             5.0.3-1                                 all          Python 3 wrapper to access docker.io's control socket
ii  python3-dockerpty                          0.4.1-2                                 all          Pseudo-tty handler for docker Python client (Python 3.x)
```

Here is a zipped version of all the files I used: [core-docker-issue.zip](https://github.com/user-attachments/files/18129400/core-docker-issue.zip)

**Comment by bharnden** [comment]
For ipv6, you would have to add the compose equivalent as well of this parameter `--sysctl net.ipv6.conf.all.disable_ipv6=0`.

Compose usage is not generally recommended at this time.

example;
```
version: '2.1'
services:
    app:
        build: .
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
```
